### ISSUE TITLE
Верстка экрана "Поиск вакансий"

### ISSUE THREAD

**Issue by SirKwest** [SirKwest/hhclient#19]
1. [Макет](https://www.figma.com/design/gAWSqZ8mbc2g0oeuKPdL19/HH-(Android)?node-id=0-1&node-type=canvas&t=CHDVVBXLmKbcKsmW-0)
2. Просто располагаем на layout нужные на странице элементы, так как они должны выглядеть на макете. Пусть они ничего не делают, только реализуем визуальные изменения у строки поиска при вводе текста.

Непонятные нюансы, на которые надо обратить внимание:
- кнопка фильтров может никуда не вести, но у неё 2 состояния визуальных, дайте любую возможность их менять (например по клику). Когда дойдем до реализации фильтров, изменим это поведение по клику
- Синий прямоугольник с результатами поиска на PlaylistMaker не присутствовал, его поведение нигде не описано, только на макете.
- У экрана есть состояние с результатами, есть "нет интернета", есть "нет результатов", есть "ошибка сервера" (экран 35 на макетах).

**Comment by sandpaper-hub** [comment]
https://github.com/SirKwest/hhclient/pull/58
