### ISSUE TITLE
Постраничная загрузка вакансий

### ISSUE THREAD

**Issue by SirKwest** [SirKwest/hhclient#22]
1. [Про пагинацию](https://practicum.yandex.ru/trainer/android-developer/lesson/ac83fdcf-a384-450c-aaaf-6f7b3ee6c1bd/?searchedText=%D0%BF%D0%B0%D0%B3%D0%B8%D0%BD%D0%B0%D1%86%D0%B8%D0%B5%D0%B9) расписано. Возможно где-то ещё, пока не нашли.
2. Закрываем все недоработки после #21 визуальные если они есть. Например, отображение прогресс бара при выполнении запроса на следующую страницу.

**Comment by mdorogov** [comment]
[Про пагинацию тут "Постраничная загрузка вакансий на экране поиска" ](https://practicum.yandex.ru/learn/android-developer/courses/8e512d47-6da3-4ab6-8464-aff40d0c0a31/sprints/257962/topics/174a1fab-ce65-4a2f-a606-4f543d30c754/lessons/e56b5398-c90a-4488-9b3e-291ddc382888/)
