### ISSUE TITLE
Вспомогательные классы и функции

### ISSUE THREAD

**Issue by SirKwest** [SirKwest/hhclient#8]
**Что сделать**:
1. При текущей структуре проекта, в пакете utils стоит добавить функционал, который будет выполнять утилитарную функцию в будущем проекте.
2. За основу что туда добавить можно взять то, что выполняло такую функцию в PlaylistMaker: функция Debounce при кликах, интерфейс OnItemClickListener для адаптеров данных для RecyclerView, SingleLiveEvent класс из экрана настроек и тп. Список не финальный, просто для вдохновения

**Comment by sandpaper-hub** [comment]
https://github.com/SirKwest/hhclient/pull/51

**Comment by SirKwest** [comment]
Я исправил все замечания detekt, добавил кое-что из "списка вдохновения" и переделал debounce extension, не потому что там было неправильно, а просто хотел попробовать такую реализацию.
